- scss/reset/_forms.scss
- yarn.lock
New `<textarea>` styles don't need a min-height, and having it messes up auto-resizing
> Removed rule to set a min-height on textareas

- scss/utils/helpers/_responsiveVarContext.scss
I've changed the name of the mixin and the vars for clarity.
> rename responsiveVarContext to match the var names it changes

- scss/reset/_forms.scss
Fixes https://meetup.atlassian.net/browse/SDS-290
An `auto` `height` helps safari align checkboxes correctly.
**Before:**
**After:**
> add safari checkbox height fix

- scss/reset/_bodyText.scss
Design team is still evaluating how type should scale across viewports.
Just commenting this out and keeping the mixin so we can easily enable type that scales with the viewport.
> Undo scaling type with browser (for now)

- scss/utils/vars/_layout.scss
These are the latest border radii the design team has agreed upon. These vars are needed for some minor button style updates in `meetup-web-components`
> Updated border radii

- scss/reset/_bodyText.scss
Needed for things like the "read more" button after the truncated descriptions on event home
> Made` %text--link` styling available to buttons

- scss/reset/_bodyText.scss
- scss/utils/vars/_type.scss
Newer designs have been using a bigger line-height for large blocks of text. This makes it the default.
> Increased line-height for runningText

- scss/utils/helpers/_type.scss
- scss/utils/vars/_color.scss
We're now using `$C_blue` as an accent color (instead of `$C_red` everywhere all of the time). As a part of this work, the design team wants to go with blue links again.
> Update default link styles

- scss/utils/helpers/_type.scss
Fixes: https://meetup.atlassian.net/browse/MW-2507
Even with the `runningText` class added to the parent div, Group Home descriptions were not wrapping correctly. This should fix and provide better browser support for text wrapping.
Before:
After:
> More stable styles for wrapping in `.runningText`

- Gruntfile.js
- scss/utils/vars/_type.scss
Added better fallbacks for Graphik.
The `-apple-system` and `BlinkMacSystemFont` values are references for Safari and Chrome to the "San Francisco" family. OSX Does not expose the system font as a normal font on disk, so this workaround is necessary.
> Sds 487/improved font stack

- scss/utils/helpers/_type.scss
https://meetup.atlassian.net/browse/MW-3010
The design doesn't want to hyphenate large blocks of text anymore.
> No more hyphens in `.runningText`

- scss/utils/helpers/_type.scss
Always wrap the entire word when it doesn't fit on 1 line - even in IE
IE11 was doing this:
> Fix wrapping for IE11

- docs/examples/mediaSizes.html
- docs/examples/spacing.html
- docs/examples/typeSpec.html
- docs/examples/typeWeight.html
Currently, [swarm-design-system](https://github.com/meetup/swarm-design-system) is creating tables for media sizes and spacing metrics in Markdown.
Giving them their own pages that get iframed into the docs will open us up to dynamically generating/updating the page content via swarm-constants
> Add pages for media sizes and spacing metrics

- scss/reset/_forms.scss
Safari adds a 2px top and bottom margin to `<button>`
> margin:0 for <button>

- scss/reset/all.scss
**Removes custom property definitions from sasstools reset**
[CONST-13](https://meetup.atlassian.net/browse/CONST-13) explains why:
> Currently, we import a `customProperties` dist to the SST reset. While this works great for modern browsers, postcss is unable to calculate a computed value because the custom property definitions are not in global scope (the SST reset never runs through the postcss-loader).
To fix this, we must...
> 1) create a new dist for scss modules
> 2) make sure we prefix selectors with `:global`, to put custom property definitions into global scope
> 3) assume that consumer apps (or platform renderer) is responsible for importing the custom properties module dist into app code
PostCSS can't get calculated values for custom properties if we import them here in …
> rm custom property dist

- Makefile
- README.md
- scss/utils/_all.scss
- scss/utils/customProperties/_responsive.scss
- scss/utils/functions/_brightness.scss
- scss/utils/functions/_color.scss
- scss/utils/helpers/_align.scss
- scss/utils/helpers/_border.scss
- scss/utils/helpers/_breakpoint.scss
- scss/utils/helpers/_browser.scss
- scss/utils/helpers/_button.scss
- scss/utils/helpers/_flexbox.scss
- scss/utils/helpers/_forms.scss
- scss/utils/helpers/_i18n.scss
- scss/utils/helpers/_shadow.scss
- scss/utils/helpers/_type.scss
https://meetup.atlassian.net/browse/SST-15
Makes all partials in `scss/utils/` self-sufficient and individually importable by explicitly declaring dependencies. This makes it easier to import a specific utility into a style module without needed to figure out its dependencies.
Also cleaned up the import order in `_all.scss` where we previously had to import things in a certain order because some helpers depended on others. Now that each util partial declares what it needs, we can deport them in any order now.
The diff between compiled CSS in this branch and compiled CSS in `master` is clean.
If you'd like to test locally, comment out all the lib and `var/` imports in `utils/_all.scss` and build. There will be no errors, as each util imports what it needs directly.
We're leaving the lib …
> Add explicit depenendices to all `utils/` partials

- scss/modifierClasses/_sticky.scss
- scss/modifierClasses/all.scss
An alternate way to do this would have been:
**scss/modifierClasses/_position.scss**
```.position--sticky {styles}```
**scss/modifierClasses/_sticky.scss**
```.sticky--top {styles}```
But I don't see us adding any other position modifiers, so this felt better.
> Added sticky position modifiers

- scss/utils/vars/_layout.scss
- scss/utils/vars/_scale.scss
Instead of just saying a variable is generated by `swarm-constants` in the docs, now we're actually linking to the `swarm-constants` docs.
> Added links to swarm-constants

- CHANGELOG.md
- Makefile
- scss/utils/helpers/_button.scss
Related issues:
https://meetup.atlassian.net/browse/MG-1776
https://meetup.atlassian.net/browse/SDS-722
This change was made to allow buttons to be re-colored to match native mobile app buttons when being rendered in a webview
> Added button style mixins

- package.json
- scss/reset/_bodyText.scss
- scss/reset/_forms.scss
- scss/reset/_headings.scss
- scss/reset/_tables.scss
- scss/utils/helpers/_type.scss
- yarn.lock
Bourbon `rem` function was still being used, and it only worked in here because a previous version of MWC had Bourbon as a dependency
> Fix font size modifiers
